#!/usr/bin/env python
import subprocess
import urllib
import re
import sys
import time


def get_server_pids(program_name):
    processes = subprocess.check_output(["ps", "-ef"])
    program_exec = "./" + program_name
    pids = []
    for line in processes.splitlines():
        items = line.split()
        if "sh " + program_exec in line or "nodejs " + program_exec in line:
            pids.append(items[1])

    return pids


def main():
    program_name = sys.argv[1]
    subprocess.check_call("./" + program_name + " 2>&1 >/dev/null &", shell=True)
    pids = []
    for _ in range(20):
        time.sleep(0.1)
        pids = get_server_pids(program_name)
        if len(pids) >= 2:
            break
    else:
        sys.exit("Server never started")

    argv = sys.argv[2:]
    argc = len(argv)
    params = {"argc": argc}
    params.update({"argv" + str(n + 1): arg for n, arg in enumerate(argv)})
    url = "http://localhost:8080?" + urllib.urlencode(params)
    exc = None
    for _ in range(100):
        time.sleep(0.1)
        try:
            content = urllib.urlopen(url).read()
            match = re.search(r"<pre>(.*)</pre>", content)
            if match:
                print(urllib.unquote(match.group(1)))
                exc = None
                break
        except IOError as e:
            exc = e

    for _ in range(100):
        time.sleep(0.1)
        subprocess.call(["kill"] + pids, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        pids = get_server_pids(program_name)
        if not pids:
            break
    else:
        sys.exit("Could not stop server")

    if exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
